const { pending } = require('./pendings.js')

console.log(Date())
pending('_transfer',0)
// pending('_transfer',1)
// pending('_transfer',2)
// pending('_transfer',3)
// pending('_transfer',4)
// pending('_transfer',5)
// pending('_transfer',6)
// pending('_transfer',7)
// pending('_transfer',8)
// pending('_transfer',9)
// pending('_transfer','a')
// pending('_transfer','A')
// pending('_transfer','b')
// pending('_transfer','B')
// pending('_transfer','c')
// pending('_transfer','C')
// pending('_transfer','d')
// pending('_transfer','D')
// pending('_transfer','e')
// pending('_transfer','E')
// pending('_transfer','f')
// pending('_transfer','F')